#define T_OPEN_TAG                      1
#define T_NOT                           2
#define T_AND                           3
#define T_OR                            4
#define T_EQ                            5
#define T_NE                            6
#define T_GT                            7
#define T_GE                            8
#define T_LT                            9
#define T_LE                           10
#define T_IN                           11
#define T_PLUS                         12
#define T_MINUS                        13
#define T_TIMES                        14
#define T_DIV                          15
#define T_MOD                          16
#define T_HTML                         17
#define T_COMMENT                      18
#define T_PRINT_OPEN                   19
#define T_PRINT_CLOSE                  20
#define T_EXTENDS                      21
#define T_CLOSE_TAG                    22
#define T_INCLUDE                      23
#define T_AUTOESCAPE                   24
#define T_CUSTOM_END                   25
#define T_CUSTOM_TAG                   26
#define T_AS                           27
#define T_CUSTOM_BLOCK                 28
#define T_SPACEFULL                    29
#define T_WITH                         30
#define T_LOAD                         31
#define T_FOR                          32
#define T_COMMA                        33
#define T_EMPTY                        34
#define T_IF                           35
#define T_ELSE                         36
#define T_IFCHANGED                    37
#define T_IFEQUAL                      38
#define T_IFNOTEQUAL                   39
#define T_BLOCK                        40
#define T_NUMERIC                      41
#define T_FILTER                       42
#define T_REGROUP                      43
#define T_BY                           44
#define T_PIPE                         45
#define T_COLON                        46
#define T_TRUE                         47
#define T_FALSE                        48
#define T_STRING                       49
#define T_INTL                         50
#define T_RPARENT                      51
#define T_LPARENT                      52
#define T_OBJ                          53
#define T_ALPHA                        54
#define T_DOT                          55
#define T_BRACKETS_OPEN                56
#define T_BRACKETS_CLOSE               57
